---
title: "class07"
author: "Larissa Rapadas"
date: "1/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
These are all of the functions:
```{r}
#This is our rescale function from the end of lecture 6
rescale <- function(x, na.rm=TRUE, plot=FALSE, ...) {
 if(na.rm) {
   rng <- range(x, na.rm=TRUE)
 } else {
  rng <-range(x)
 }

 answer <- (x - rng[1]) / (rng[2] - rng[1])
 if(plot) {
 plot(answer, ...)
 }
 return(answer)
}
```

```{r}
x <- c(1, 2, NA, 3, NA)
y <- c(NA, 3, NA, 3, 4)

function(x, y) {
  ## Print some info on where NA's are as well as the number of them 
  if(length(x) != length(y)) {
    stop("Input x and y should be vectors of the same length", call.=FALSE)
  }
  na.in.both <- ( is.na(x) & is.na(y) )
  na.number  <- sum(na.in.both)
  na.which   <- which(na.in.both)

  message("Found ", na.number, " NA's at position(s):", 
          paste(na.which, collapse=", ") ) 
  
  return( list(number=na.number, which=na.which) )
}
```

## Now, let's work with data frames: `data.frame()`.
df1, df2, and df3 have been loaded in the workspace.
```{r}
x <- df1$IDs
y <- df2$IDs

# We can see what the two df's have in common.

# We can use the function intersect() to do this for us:
intersect(x,y)

# We can also use the %in% to generate a logical vector:
x %in% y
x[x %in% y] #this effectively subsets only the variables that also exist in y

# We can now cbind() these these results...
cbind( x[ x %in% y ], y[ y %in% x ] )

```
```{r}
# Make this snippet into a first function
gene_intersect <- function(x, y) {
 cbind( x[ x %in% y ], y[ y %in% x ])
}

gene_intersect2 <- function(df1, df2) {
  cbind( df1[ df1$IDs %in% df2$IDs, ], 
         df2[ df2$IDs %in% df1$IDs, ], "exp")
}

gene_intersect(x,y)

gene_intersect3 <- function(df1, df2, gene.colname = "IDs") {
   cbind( df1[ df1[,gene.colname] %in% df2[,gene.colname], ],
          exp2=df2[ df2[,gene.colname] %in% df1[,gene.colname], "exp"] )

}

gene_intersect(x,y)

gene_intersect4 <- function(df1, df2, gene.colname = "IDs") {
  df1.name <- df1[,gene.colname]
  df2.name <- df2[,gene.colname] 
  
  df1.inds <- df1.name %in% df2.name
  df2.inds <- df2.name %in% df1.name
  
  cbind( df1[df1.inds,], 
         exp2= df2[df2.inds,], "exp")

}

gene_intersect4(df1, df2, "IDs")

```

```{r}
ggplot(data=iris, aes(x = Sepal.Length, y=Sepal.Width)) + geom_point(size = 3)
```


